#!/bin/bash
if [ -x "$(command -v ssh-agent)" ]; then
  export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"
fi

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export GLFW_IM_MODULE=ibus

if [ -d "/home/linuxbrew/.linuxbrew" ]; then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  export EXPORT_HOMEBREW_SHELLENV=1
elif [ -d "${HOME}/.linuxbrew" ]; then
  eval "$(${HOME}/.linuxbrew/bin/brew shellenv)"
  export EXPORT_HOMEBREW_SHELLENV=1
fi
export PATH="${HOME}/bin:${PATH}"
export EXPORT_HOME_BIN=1

export DESKTOP_SESSION=goobuntu-custom
export XSECURELOCK_PAM_SERVICE=xsecurelock

export TERMINAL=kitty

export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export QT_AUTO_SCREEN_SCALE_FACTOR=1

xset -b
xsetroot -solid "#000000"

xrdb -merge "${HOME}/.Xresources"
exec i3
