#!/bin/bash
if [ -x "$(command -v ssh-agent)" ]; then
  eval "$(ssh-agent -s)"
fi

export PATH="${HOME}/bin:${PATH}"
export PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
export PATH="/home/linuxbrew/.linuxbrew/sbin:${PATH}"

export DESKTOP_SESSION=goobuntu-custom
export XSECURELOCK_PAM_SERVICE=xsecurelock

export TERMINAL=kitty

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

export GDK_SCALE=2
export GDK_DPI_SCALE=0.5
export QT_AUTO_SCREEN_SCALE_FACTOR=1

xset -b
xsetroot -solid "#000000"

xrdb -merge "${HOME}/.Xresources"
exec i3
