" Basic Configuration
set nocompatible
filetype off
set shell=/bin/bash
set encoding=utf8
set mouse=a
set nonumber
set signcolumn=yes
set hlsearch
set smartindent
set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set cursorline
set foldmethod=marker
let mapleader=';'
nnoremap <c-c> <esc>
nnoremap \ :nohlsearch<cr>
map <c-a> <nop>
map <c-q> <nop>
map q <nop>

" Plugin Manager (begin)
call plug#begin('~/.vim/bundle')

Plug 'google/vim-maktaba'
Plug 'google/vim-glaive'

" Project Setup
Plug 'cherrry/1ndependence.vim'
Plug 'editorconfig/editorconfig-vim'

" Color Scheme
Plug 'fnune/base16-vim', {'commit': '00a414d'}

" Syntax Files
Plug 'tpope/vim-git'
Plug 'bfrg/vim-cpp-modern'
Plug 'ap/vim-css-color'
Plug 'pangloss/vim-javascript'
Plug 'elzr/vim-json'

" UI Display
Plug 'mhinz/vim-startify'
Plug 'itchyny/lightline.vim'
Plug 'Yggdroot/indentLine'
Plug 'mhinz/vim-signify'

" Language Server
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'dense-analysis/ale'
Plug 'rhysd/vim-lsp-ale'

" Editing
Plug 'scrooloose/nerdcommenter'
Plug 'google/vim-codefmt'

" Navigation
Plug 'othree/eregex.vim'
Plug 'chaoren/vim-wordmotion'
Plug 'RRethy/vim-illuminate'

" Project Explorer
Plug 'lambdalisue/fern.vim'
Plug 'lambdalisue/nerdfont.vim'
Plug 'lambdalisue/fern-renderer-nerdfont.vim'

" Plugin Manager (end)
call plug#end()
call glaive#Install()

" Basic Configuration (con't)
filetype plugin indent on

" Scroll Behavior
nnoremap <c-j> 2<c-e>
nnoremap <c-k> 2<c-y>

" Color Scheme
set fillchars=vert:│
set background=dark
set termguicolors
colorscheme base16-classic-dark
highlight Comment cterm=italic
highlight Normal ctermbg=None guibg=NONE
highlight link LspCxxHlGroupEnumConstant cppConstant
highlight link LspCxxHlGroupNamespace cppConstant
highlight link LspCxxHlGroupMemberVariable Normal

" Indent Guides
set list listchars=tab:\▏\ ,trail:·
let g:indentLine_char='▏'

" Startify
let g:startify_change_to_vcs_root=1
let g:startify_fortune_use_unicode=1
let g:startify_lists = [
      \ { 'type': 'bookmarks', 'header': ['Bookmarks'] },
      \ { 'type': 'dir', 'header': ['Most Recents'] },
      \ ]
let g:startify_bookmarks = [
      \ '~/.vimrc',
      \ ]

" Lightline
let g:lightline={
      \ 'colorscheme': 'wombat',
      \ 'subseparator': {'left': '│', 'right': '│'},
      \ }
set laststatus=2
set noshowmode

let g:vim_json_syntax_conceal=0

" Language Server
let g:ale_linters={}
let g:ale_linters_explicit=1
if executable('pyls')
  autocmd User lsp_setup call lsp#register_server({
        \   'name': 'pyls',
        \   'cmd': {server_info->['pyls']},
        \   'allowlist': ['python'],
        \ })
endif

function! s:on_lsp_buffer_enabled() abort
  setlocal omnifunc=lsp#complete
  if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
  nmap <buffer> K <plug>(lsp-hover)
endfunction

augroup lsp_install
  au!
  autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

" Tab Completion
inoremap <expr> <tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <expr> <s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
inoremap <expr> <cr> pumvisible() ? asyncomplete#close_popup() . "\<cr>" : "\<cr>"

" Navigation
let g:fern#renderer = "nerdfont"
nnoremap <c-n> :Fern . -drawer -toggle<cr>

" Fix delete
set backspace=2
