" Basic Configuration
set nocompatible
filetype off
set shell=/bin/bash
set encoding=utf8
set mouse=a
set nonumber
set signcolumn=yes
set hlsearch
set smartindent
set autoindent
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set cursorline
let mapleader=';'
nnoremap <C-c> <silent> <C-c>
nnoremap \ :nohlsearch<Cr>

" Plugin Manager (begin)
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'google/vim-maktaba'
Plugin 'google/vim-glaive'

" Project Specific
Plugin 'cherrry/1ndependence.vim'
Plugin 'editorconfig/editorconfig-vim'

" Color Scheme
Plugin 'chriskempson/base16-vim'

Plugin 'itchyny/lightline.vim'
Plugin 'Yggdroot/indentLine'

" Code Editing
Plugin 'neoclide/coc.nvim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'google/vim-codefmt'

" Code Searching
Plugin 'othree/eregex.vim'

" Language Files
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'ap/vim-css-color'
Plugin 'pangloss/vim-javascript'
Plugin 'elzr/vim-json'

" Plugin Manager (end)
call vundle#end()
call glaive#Install() 

" Basic Configuration (con't)
filetype plugin indent on

" Scroll Behavior
nnoremap <C-j> 2<C-e>
nnoremap <C-k> 2<C-y>

" Color Scheme
colorscheme base16-default-dark
set termguicolors
syntax on
hi Normal ctermbg=None guibg=NONE
hi Comment cterm=italic

" Indent Guides
set list lcs=tab:\▏\ 
let g:indentLine_char='▏'

" Lightline
let g:lightline={'colorscheme':'wombat'}
set laststatus=2
set noshowmode

let g:vim_json_syntax_conceal=0

" CodeFmt
Glaive codefmt plugin[mappings]

" Code Completion
inoremap <silent><expr> <tab>
      \ pumvisible() ? "\<c-n>" :
      \ <sid>check_back_space() ? "\<tab>" :
      \ coc#refresh()
inoremap <expr><s-tab> pumvisible() ? "\<c-p>" : "\<c-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Fix delete
set backspace=2
